# docker-compose.yml

version: '3'

networks:
  development:
    driver: bridge
    
services:
  frontend:
    container_name: frontend_container
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      - development
    environment:
      - VITE_API_ENDPOINT=http://localhost:4000


  backend:
    container_name: backend_container
    build: 
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    networks:
      - development

  nginx:
    container_name: nginx_container
    build: 
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "5005:80"
    networks:
      - development
    depends_on:
      - frontend
      - backend 
  
